language: node_js
node_js:
  - "6"
cache:
  - node_modules
install:
  - npm install
  - npm install coveralls
script:
  - npm run lint
  - npm run coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
